name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Flask App to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 100.55.89.191
          username: root
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /root/devops-aws-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f app.py || true
            nohup python3 app.py > output.log 2>&1 &
